# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in magneto-serge-rspec.gemspec
gemspec

gem 'rake', '~> 13.0'
gem 'rspec', '~> 3.0'
gem 'rubocop', '~> 1.21'

# For examples
gem 'http', '~> 5.0'
