/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum ProxyMode {
  Auto = 0,
  Record = 1,
  Replay = 2,
  Passthrough = 3
}
export declare function version(): string
export declare class MagnetoProxy {
  constructor(cassetteDir: string)
  setPort(port: number): void
  setMode(mode: ProxyMode): void
  startRecording(cassetteName: string): void
  stopRecording(): void
  replay(cassetteName: string): void
  shutdown(): void
  getPort(): number
}
